// English glossary descriptions. Term keys mirror ru.js exactly.
// Only `desc` is needed here — `full` is shared from ru.js.
// Missing entries fall back to the Russian description, so the site works
// even with a partially translated glossary.

export const ENTRIES = {
  // --- Hardware & peripherals ---
  'MCU':       { desc: 'Microcontroller — an integrated circuit that packs CPU, memory and peripherals into one chip. The ET Max uses an STM32F405.' },
  'FPU':       { desc: 'Hardware unit for float operations. On the Cortex-M4F it executes VMUL.F32 in 1 cycle. The Cortex-M3 has no FPU and falls back to soft-float.' },
  'MOSFET':    { desc: 'Power field-effect transistor. The 3-phase EUC bridge uses 6 of them: a high-side and low-side switch on each phase.' },
  'PWM':       { desc: 'Pulse-width modulation. Rapidly switching a transistor between on and off; the average voltage equals duty × Vbus. The ET Max runs PWM at 20 kHz.' },
  'ADC':       { desc: 'Analog-to-digital converter, turning analog signals (voltage, current) into digital codes. The STM32F405 ADC is 12-bit, up to 2.4 MSPS.' },
  'DAC':       { desc: 'Digital-to-analog converter. Not used in the ET Max.' },
  'SPI':       { desc: 'Synchronous serial interface: MOSI, MISO, SCK, CS. SPI1 of the ET Max talks to the MPU6500 IMU.' },
  'UART':      { desc: 'Asynchronous serial interface, two wires (TX, RX) plus ground. Used for the BMS link and the BLE module.' },
  'USART':     { desc: 'A UART that also supports synchronous mode. USART1 on the STM32F405 carries BLE telemetry.' },
  'GPIO':      { desc: 'General-purpose digital pin. Can act as input, output, or one of the alternate functions (TIM1_CH1, USART1_TX and so on).' },
  'DMA':       { desc: 'Direct memory access engine. Copies data between peripheral and RAM without CPU help.' },
  'NVIC':      { desc: 'Nested vectored interrupt controller in the Cortex-M. Handles ISR priorities, nesting, and tail-chaining.' },
  'ISR':       { desc: 'Interrupt service routine. The main FOC ISR fires 20,000 times per second on TIM1 update.' },
  'EXTI':      { desc: 'External interrupt controller. Used for Hall sensor edges and button events.' },
  'HSE':       { desc: 'External high-speed oscillator — a crystal in the 8–25 MHz range. The ET Max takes an 8 MHz HSE up to 168 MHz through the PLL.' },
  'PLL':       { desc: 'Phase-locked loop. Inside the STM32 it multiplies HSE up to 168 MHz SYSCLK. Inside HFI it tracks θ_est toward θ_true, holding sin(2·θ_err) near zero.' },
  'SVD':       { desc: 'XML file describing every peripheral register on a given chip. ST publishes .svd files for the entire STM32 lineup.' },
  'BLE':       { desc: 'Low-energy variant of Bluetooth. Used to talk to companion apps like EUC World and WheelLog.' },
  'GATT':      { desc: 'Generic attribute profile of BLE for structured data. The wheel publishes telemetry as GATT notifications.' },
  'BMS':       { desc: 'Battery management system board. Balances cells, protects against over-charge / over-discharge / over-temperature, and reports state over UART.' },
  'NTC':       { desc: 'Negative-temperature-coefficient thermistor: resistance drops as temperature rises. Mounted on the motor stator and the controller PCB.' },
  'MEMS':      { desc: 'Microelectromechanical system. The accelerometer and gyroscope inside the MPU6500 are MEMS: a tiny silicon mass on micro-machined springs.' },

  // --- STM32 internals ---
  'TIM1':      { desc: 'STM32F4 advanced-control timer. Generates 3-phase PWM with complementary outputs and dead-time. The backbone of motor control.' },
  'TIM8':      { desc: 'A second advanced-control timer, functionally identical to TIM1. In some configurations it works in tandem with TIM1.' },
  'BDTR':      { desc: 'Break and Dead-Time Register of TIM1/TIM8. Sets the dead-time between complementary switching and how the timer reacts to a break signal.' },
  'TRGO':      { desc: 'Trigger output of a timer for synchronizing other blocks. TIM1 TRGO triggers the ADC to sample current at the middle of the PWM period.' },
  'CCR':       { desc: 'Capture/compare register of a TIM. The value in CCRx defines the duty cycle of a PWM channel.' },
  'JDR':       { desc: 'Injected data register of the ADC. Holds the result of an injected conversion right after JEOC.' },
  'JEOC':      { desc: 'Injected end-of-conversion flag in ADC_SR. When set, the injected conversion is done and JDRx holds the result.' },
  'AHB':       { desc: 'Main internal bus of the STM32. On the F405, AHB runs at 168 MHz and clocks the core plus the high-speed peripherals.' },
  'APB':       { desc: 'Peripheral buses of the STM32. On the F405: APB1 = 42 MHz, APB2 = 84 MHz. APB clocks the TIMs, ADC, SPI, USART and friends.' },
  'SRAM':      { desc: 'Static RAM. The STM32F405 has 192 KB starting at 0x20000000. The motor_state struct lives here.' },
  'RDP':       { desc: 'Read-out protection of the firmware. Level 0 — none, Level 1 — flash cannot be read but can be erased, Level 2 — irreversible lockdown.' },
  'SWD':       { desc: 'ARM 2-wire debug interface: SWDIO (data) + SWCLK (clock). Replaces the bulkier JTAG.' },
  'SWDIO':     { desc: 'Bidirectional data line of SWD. On STM32 it sits on PA13.' },
  'SWCLK':     { desc: 'Clock line of SWD, runs up to 4 MHz. On STM32 it sits on PA14.' },
  'YMODEM':    { desc: 'A serial-line file-transfer protocol with CRC. The STM32 bootloader uses it for OTA firmware updates.' },
  'POR':       { desc: 'Power-on reset of the microcontroller. The first stage in the firmware lifecycle.' },
  'OTA':       { desc: 'Over-the-air firmware update over BLE, no need to open the case.' },
  'IAP':       { desc: 'In-application programming: writing flash from the running application. The bootloader uses it to commit a YMODEM-received image.' },

  // --- Motor control ---
  'BLDC':      { desc: 'Brushless DC motor. Permanent-magnet rotor, wound stator, electronic commutation.' },
  'PMSM':      { desc: 'Permanent-magnet synchronous motor. Physically the same as a BLDC, but driven by sinusoidal currents through FOC.' },
  'FOC':       { desc: 'Vector control of a motor. Splits the current into Iq (torque) and Id (flux) in a frame that rotates with the rotor.' },
  'PID':       { desc: 'Classic three-term controller: proportional (P), integral (I), derivative (D).' },
  'PI':        { desc: 'Controller with no D term. FOC uses two PI loops — one on the D axis, one on the Q axis — that track the target currents.' },
  'PD':        { desc: 'Controller with no I term. Used by the EUC balance loop: Iq_target = -(Kp·angle + Kd·rate). An I term in the balance loop does more harm than good.' },
  'Clarke':    { desc: 'Clarke transform: three-phase currents (a,b,c) into two orthogonal axes (α,β). One step on the way from phases to D-Q.' },
  'Park':      { desc: 'Park transform: stationary α,β into D,Q rotating with the rotor. In D,Q the steady-state currents are constants.' },
  'SVPWM':     { desc: 'Space-vector PWM. Squeezes ~15% more bus voltage than plain sinusoidal PWM by injecting a common-mode component into all three phases.' },
  'Kv':        { desc: 'Motor speed constant in RPM per volt. The ET Max sits at ~14.5 RPM/V: free-running on 168 V the rotor would spin around 2,430 RPM.' },
  'Kp':        { desc: 'Proportional gain of a controller. In EUC balance terms this is the Hardness setting (pedal stiffness).' },
  'Ki':        { desc: 'Integral gain of a controller. In FOC current loops it compensates for Rs and back-EMF.' },
  'Kd':        { desc: 'Derivative gain of a controller. In EUC balance terms this is the Damping setting (pedal recovery).' },
  'back-EMF':  { desc: 'The voltage induced into the stator windings by a spinning rotor, proportional to speed. The Flux Observer integrates back-EMF to estimate the rotor angle.' },
  'EMF':       { desc: 'Electromotive force. In a motor context the relevant flavor is back-EMF (counter-EMF).' },
  'Flux Observer': { desc: 'Magnetic flux observer. Estimates the rotor angle from back-EMF without position sensors. Reliable above roughly 5 km/h.' },
  'MTPA':      { desc: 'Maximum-torque-per-ampere strategy below base speed: the most torque for the current you spend. Id rides the optimal curve.' },
  'MTPV':      { desc: 'Maximum-torque-per-volt strategy above base speed: the most torque for the voltage available. Works alongside field weakening.' },
  'Field Weakening': { desc: 'Weakening the magnetic field by injecting negative Id, reducing total flux in the machine. Extends the speed range above base.' },
  'HFI':       { desc: 'Sensorless rotor-angle estimation at zero or low speed. A 0.5–2 kHz carrier rides on the estimated d-axis; the q-current response carries sin(2·θ_err). Requires saliency (Lq ≠ Ld), so it works on IPM motors and is nearly useless on SPM.' },
  'IPM':       { desc: 'Interior permanent magnet — a PMSM where the magnets are buried inside the rotor iron. Flux along and across the magnet sees different paths, so Lq runs noticeably larger than Ld (ratio 1.5–3). That saliency is what HFI feeds on.' },
  'SPM':       { desc: 'Surface permanent magnet — a PMSM with magnets glued onto the rotor surface. Lq ≈ Ld (ratio 1.05–1.1), almost no saliency. Cheaper and simpler than IPM, but HFI does not work. The ET Max hub motor is SPM.' },
  'Ld':        { desc: 'Stator inductance along the d axis (along the rotor magnet). On an IPM it is smaller than Lq because the flux path runs into the magnet and a wider effective air gap. Appears in di_d/dt = (V_d − R·i_d + ω·Lq·i_q) / Ld.' },
  'Lq':        { desc: 'Stator inductance along the q axis (across the magnet). On an IPM it is larger than Ld: the flux path runs through iron and meets less reluctance. The 1/Ld − 1/Lq difference is the useful HFI signal.' },
  'saliency':  { desc: 'The motor saliency, i.e. the Lq/Ld ratio. IPM is 1.5–3, SPM is 1.05–1.1. The HFI signal amplitude scales linearly with this number; at 1.0 it vanishes.' },
  'явнополюсность': { desc: 'Russian for saliency: the inductance difference along the d and q axes. The property that lets you find the rotor angle from the response to a probe voltage.' },
  'несущая':   { desc: 'Russian for carrier: a high-frequency signal (typically 0.5–2 kHz) that carries no information by itself, but its modulation hides the useful signal. In HFI the carrier is applied to the estimated d axis, and the angle error appears in the q-current amplitude at the same frequency.' },
  'демодулятор': { desc: 'Russian for demodulator: the block that pulls the useful signal out of the carrier modulation. In HFI it multiplies the measured iq by cos(ω_h·t) and lowpasses the result, leaving 0.5·sin(2·θ_err).' },
  'LPF':       { desc: 'Low-pass filter: lets slow components through, attenuates fast ones. In HFI it strips the doubled-carrier harmonic from the demodulator output. The simplest form is one-pole: y += α·(x − y), where α sets the cutoff.' },
  'ФНЧ':       { desc: 'Russian for low-pass filter (LPF). Lets slow signals through, suppresses fast harmonics. Firmware implementations are usually one- or two-pole IIR.' },
  'field weakening': { desc: 'Weakening the magnetic field by injecting negative Id, reducing total flux in the machine. Extends the speed range above base.' },
  'FW':        { desc: 'Field Weakening. Negative Id injected to extend the speed range above base.' },
  'Dead-time': { desc: 'A pause between turning off one switch and turning on the other on the same phase. Prevents shoot-through of the bridge. The ET Max uses 571 ns.' },
  'dead-time': { desc: 'A pause between turning off one switch and turning on the other on the same phase. Prevents shoot-through of the bridge. The ET Max uses 571 ns.' },
  'Hall':      { desc: 'A Hall-effect sensor that reads the rotor magnetic field. Three sensors yield 6 discrete positions per electrical revolution, enough to start a BLDC.' },
  'Iq':        { desc: 'Current along the Q axis (torque). It is what produces torque in a PMSM; the EUC balance loop drives Iq directly.' },
  'Id':        { desc: 'Current along the D axis (flux, magnetizing). Held at zero in normal operation, driven negative in field weakening.' },
  'Vq':        { desc: 'Voltage along the Q axis, the output of the Iq PI controller. Goes back to phase voltages through Inverse Park.' },
  'Vd':        { desc: 'Voltage along the D axis, the output of the Id PI controller.' },
  'RMS':       { desc: 'Root mean square. For a sinusoid RMS = peak / √2. I²R losses are computed using RMS current.' },
  'IMU':       { desc: 'Inertial measurement unit. The MPU6500 is a 6DOF IMU: 3-axis accelerometer plus 3-axis gyroscope.' },
  'DOF':       { desc: 'Degrees of freedom of a sensor. 6DOF = 3 accel axes + 3 gyro axes. 9DOF adds a magnetometer.' },
  'LUT':       { desc: 'Look-up table of precomputed values. The ET Max firmware uses LUTs for sin/cos (256 points), atan2, and inverse square roots.' },
  'LSB':       { desc: 'Least significant bit. The quantization step of an ADC, DAC, or sensor. The MPU6500 accelerometer at ±2g yields 16,384 LSB/g.' },

  // --- Safety / telemetry ---
  'tiltback':  { desc: 'Firmware-driven backward pedal tilt that forces the rider to slow down. Triggers on overspeed, overheat, or low battery.' },
  'Tiltback':  { desc: 'Firmware-driven backward pedal tilt that forces the rider to slow down. Triggers on overspeed, overheat, or low battery.' },
  'cutout':    { desc: 'Emergency motor shutdown. All MOSFETs are forced off and the rider falls forward. Triggers on overcurrent or loss of BMS communication.' },
  'Cutout':    { desc: 'Emergency motor shutdown. All MOSFETs are forced off and the rider falls forward. Triggers on overcurrent or loss of BMS communication.' },
  'CUTOUT':    { desc: 'Emergency motor shutdown. All MOSFETs are forced off and the rider falls forward. Triggers on overcurrent or loss of BMS communication.' },
  'HPF':       { desc: 'High-pass filter. Lets fast changes through, suppresses slow drift and DC offset. Used inside the Flux Observer.' },
  'I²R':       { desc: 'Joule\'s law: power loss in a conductor is P = I²·R. For a 3-phase system with RMS current: P = 1.5 × I² × Rs.' },
  'duty cycle':{ desc: 'PWM duty cycle: the fraction of time the signal sits at "1". Set through the timer\'s CCRx register.' },
  'Duty cycle':{ desc: 'PWM duty cycle: the fraction of time the signal sits at "1". Set through the timer\'s CCRx register.' },

  // --- Specific identifiers used in the anthology ---
  'STM32F405': { desc: 'The main microcontroller of the Begode ET Max. ARM Cortex-M4F with FPU, 168 MHz, 1 MB flash, 192 KB SRAM, advanced timers TIM1+TIM8 with dead-time.' },
  'STM32F103': { desc: 'Microcontroller of the older Begode models such as the RS C30. ARM Cortex-M3 without FPU, 72 MHz, 64 KB flash, 20 KB SRAM.' },
  'MPU6500':   { desc: '6DOF IMU from InvenSense. ±2…±16g accelerometer plus ±250…±2000 °/s gyroscope in a 3×3 mm package. Talks SPI at 1 MHz.' },
  'ET Max':    { desc: 'A 2023 EUC model from Begode. STM32F405, 168 V nominal, peak motor power around 30 kW. The reference platform of this anthology.' },
  'motor_state': { desc: 'Global RAM struct holding the motor state at 0x200000A0, about 84 bytes. Every ISR and main-loop task exchanges FOC, balance and telemetry state through it.' },
  'iq_target': { desc: 'Target Q-axis current (traction). Output of the balance PD controller, input of the current PI. Lives at motor_state + 0x18.' },
  'D-Q':       { desc: 'The two-axis rotor frame: D (direct, along the field) and Q (quadrature, along the torque). All FOC math happens in this frame.' },
  'Thumb2':    { desc: 'ARM Cortex-M instruction set in 16/32-bit form. The whole STM32 firmware is Thumb2 code; Ghidra decompiles it back to C-like pseudocode.' },
  'gcc-arm':   { desc: 'GCC cross-compiler for ARM Cortex-M. The standard tool for STM32 firmware. The ET Max image carries -O2 fingerprints from it.' },
  'Begode':    { desc: 'Chinese EUC manufacturer (formerly GotWay). Has built electric unicycles since 2014, including the ET Max this anthology builds on.' },
  'InvenSense':{ desc: 'A MEMS-sensor maker, now part of TDK. Their MPU-6050 / 6500 / 9250 sit inside almost every modern EUC, drone, and e-scooter.' },

  // --- ARM assembly & float ---
  'VMUL.F32':  { desc: 'ARM Thumb2 hardware-FPU instruction: multiplies two single-precision floats (32-bit) in 1 cycle. Available on Cortex-M4F and up.' },
  'VADD.F32':  { desc: 'ARM Thumb2 FPU instruction: adds two single-precision floats in 1 cycle. On the Cortex-M3 (no FPU) the compiler falls back to __aeabi_fadd.' },
  'VSUB.F32':  { desc: 'ARM Thumb2 FPU instruction: subtracts floats in 1 cycle.' },
  'VDIV.F32':  { desc: 'ARM Thumb2 FPU instruction: divides floats. Slow even with FPU — 14 cycles. Used sparingly in control code.' },
  '__aeabi_fmul': { desc: 'GCC software helper for float multiplication on ARM cores without FPU (Cortex-M3 and the like). 60–100 cycles per op against 1 with FPU.' },
  '__aeabi_fadd': { desc: 'GCC software helper for float addition on ARM cores without FPU. Roughly 50–80 cycles per op.' },
  'Q15':       { desc: 'Fixed-point format: a 16-bit word with 15 fractional bits and 1 sign bit. Range −1…+1 with step 2⁻¹⁵ ≈ 3·10⁻⁵. The bedrock of integer DSP on the Cortex-M3.' },
  'Q16':       { desc: 'Fixed-point format with 16 fractional bits. The ET Max firmware uses it for the electrical angle: 0…65535 maps to 0…360°.' },
  'fixed-point': { desc: 'Integer arithmetic with an implied decimal point. Faster than float on cores without FPU, but the developer scales values by hand.' },
  'soft-float':{ desc: 'Software emulation of float through the GCC runtime, used when the core has no FPU. An operation costs tens of cycles instead of one.' },
  'Cortex-M3': { desc: 'ARM core with no FPU and no SIMD, pure 32-bit integer. Found in the STM32F103. To run FOC there you need fixed-point math.' },
  'Cortex-M4F':{ desc: 'ARM core with a hardware single-precision FPU. Found in the STM32F405. A single-cycle float math is what fits the full FOC into a 50-µs ISR.' },

  // --- Reverse-engineered functions and identifiers ---
  'Math_PI_Controller': { desc: 'PI controller with anti-windup. Takes (target, measured, struct_ptr) and returns the requested voltage. The struct holds Kp, Ki, the integral, and output limits.' },
  'Math_Park_Inverse':  { desc: 'Inverse Park transform: converts (Vd, Vq) in the rotating d/q frame back to (Vα, Vβ) in the stationary α/β frame. Works the same way for currents.' },
  'Math_Atan2_LUT':     { desc: 'Fast atan2 through a table. Returns the angle in Q15 format (0…65535 = 0…360°). With FPU it would be a single atan2f call; via LUT it costs about ten cycles.' },
  'Math_Slew_Rate_Limiter': { desc: 'Slew-rate limiter. Takes (current, max_step) and returns the value bounded by step size. Keeps field weakening from snapping around.' },
  'Math_Trig_Fast_SinCos':  { desc: 'Fast sin/cos through a 256-point LUT with linear interpolation. Around 10 cycles instead of about 50 for sinf/cosf.' },
  'Math_Limit_Value':       { desc: 'A simple clamp: value clipped to ±max. Applied to PI outputs before they are written to TIM CCR.' },
  'Control_Flux_Observer_Update': { desc: 'The main flux observer routine. Reads ADC and voltage, integrates back-EMF into flux_alpha/flux_beta, returns a refined rotor angle.' },
  'Control_Flux_Observer_Angle':  { desc: 'Returns the latest rotor angle from the flux observer. Caches the most recent atan2 of the flux vector.' },
  'Control_Motor_FOC_Update':     { desc: 'Main FOC ISR at 20 kHz. Reads currents from the ADC, runs Park, two PI loops, the inverse transforms, SVPWM, then writes CCRx of the timer. At address 0x08013974.' },
  'Control_IMU_Fusion_Step':      { desc: 'One step of the complementary IMU filter. Fuses accelerometer and gyro with α≈0.98 and writes the packed angle and rate into motor_state.' },
  'Control_SVPWM_Modulation_Limit': { desc: 'SVPWM modulation limiter. If |V|² > V_max² it scales Vd, Vq through an inverse-square-root LUT. At address 0x00014C00.' },
  'Control_Telemetry_Task':       { desc: 'Telemetry and supervisor task at about 5 Hz. Builds a 20-byte 0x55AA packet, checks thresholds (speed, temperature, PWM) and raises an alarm on overrun. At address 0x08018C2C.' },
  'ADC_Get_Phase_Currents':       { desc: 'Reads two phase currents from the ADC injected registers ADC1->JDR1 / JDR2 and applies the calibrated offset. The third phase is computed as ic = -(ia + ib).' },
  'HAL_PWM_Set_Duty_Cycle':       { desc: 'Writes three duty values into TIM1->CCR1 / CCR2 / CCR3. They take effect on the next timer update event.' },
  'HAL_GPIO_WritePin':            { desc: 'Sets or clears a GPIO pin. Direct write to BSRR (atomic).' },
  'HAL_GPIO_Init_AF':              { desc: 'Configures a GPIO into Alternate Function mode: sets MODER and AFRH/AFRL to wire the pin to a peripheral (USART, TIM and so on).' },
  'HAL_SPI_TransmitReceive':      { desc: 'Half-duplex SPI transfer that writes one buffer and reads back a same-length response. Used to read all 14 bytes of IMU data in one shot.' },
  'HAL_UART_Init':                { desc: 'UART initialization: baud rate, frame format, parity, mode (RX, TX, RXTX), flow control.' },
  'HAL_UART_Control_UE':          { desc: 'Enables or disables a UART through the UE bit of CR1.' },
  'HAL_TIM_PWM_Init':             { desc: 'Initializes a timer in PWM mode: prescaler, period, alignment (center-aligned), polarity.' },
  'HAL_ADC_Init':                 { desc: 'Initializes an ADC: resolution, scan mode, trigger source, data alignment.' },
  'HAL_SPI_Init':                 { desc: 'Initializes an SPI: master/slave mode, CPOL, CPHA, baud-rate prescaler, frame size (8/16-bit).' },
  'HAL_Delay':                    { desc: 'Blocking delay in milliseconds via SysTick. Must not be called from an ISR — use it only in the main loop.' },
  'HAL_GetTick':                  { desc: 'Current SysTick counter in milliseconds. Used for timeouts and non-blocking waits.' },
  'mpu_read_gyro':                { desc: 'High-level wrapper around an SPI read of the MPU6500 gyro registers (0x43…0x48). Returns three int16 values along XYZ.' },
  'mpu_read_reg':                 { desc: 'Reads one MPU6500 register over SPI. Address with the READ bit (0x80) — send — receive a byte.' },
  'mpu_write_reg':                { desc: 'Writes one MPU6500 register: address without the READ bit, then value.' },
  'flux_obs':                     { desc: 'Global flux-observer state struct: flux_alpha, flux_beta, offset_a, offset_b, plus two integrators with an HPF (τ ≈ 50 ms).' },
  'gyro_bias_x':  { desc: 'Calibrated gyro zero offset along X (in LSB). Computed at boot by averaging 200 samples.' },
  'gyro_bias_y':  { desc: 'Calibrated gyro zero offset along Y. Part of the boot calibration.' },
  'gyro_bias_z':  { desc: 'Calibrated gyro zero offset along Z. Part of the boot calibration.' },
  'current_offset_a': { desc: 'ADC offset for the phase-A shunt. Averaged over ~100 samples with the bridge off. Without it the measured current would carry a constant tens-of-amps bias.' },
  'current_offset_b': { desc: 'ADC offset for the phase-B shunt. Same idea as current_offset_a.' },
  'system_state':                 { desc: 'Global flag holding the firmware\'s current stage. Updated inside Logic_Settings_And_Buttons. Values: STATE_POR, STATE_BOOT_DONE, STATE_IDLE_LEVEL, STATE_ARMED, STATE_RUNNING, STATE_TILTBACK, STATE_FAULT.' },
  'Logic_Settings_And_Buttons':   { desc: 'State-machine dispatcher. Called from the main loop, it checks conditions and updates system_state. At address 0x08013354.' },
  'pedal_switch_active':          { desc: 'Returns true when the inductive or optical weight-on-pedal sensor detects a rider. Used in the IDLE → ARMED transition.' },
  'TIM1->BDTR':                   { desc: 'Break and Dead-Time Register of TIM1. Holds DTG[7:0] (dead-time), MOE (master output enable), AOE, BKE, and the break behavior.' },
  'TIM1->CCR1':                   { desc: 'Compare register of TIM1 channel 1. The written value sets the PWM transition point. CCR1 = 0 → 0% duty, CCR1 = ARR → 100%.' },
  'TIM1->CCR2':                   { desc: 'Compare register of TIM1 channel 2 (phase B).' },
  'TIM1->CCR3':                   { desc: 'Compare register of TIM1 channel 3 (phase C).' },
  'TIM1->SR':                     { desc: 'Status register holding UIF (update), CCxIF (compare match), BIF (break) and so on. The ISR starts by reading UIF and ends by clearing it.' },
  'RCC->CR':                      { desc: 'Clock Control Register: HSEON / HSERDY (external oscillator), HSION / HSIRDY (internal RC), PLLON / PLLRDY.' },
  'RCC->CFGR':                    { desc: 'Clock Configuration Register: SW (system clock source), HPRE / PPRE (AHB / APB dividers), MCO output.' },
  'RCC->PLLCFGR':                 { desc: 'PLL Configuration: PLLM (input divider), PLLN (multiplier), PLLP (output divider for SYSCLK), PLLQ (for USB / SDIO).' },
  'FLASH->ACR':                   { desc: 'Flash Access Control: LATENCY (wait states), PRFTEN (prefetch), ICEN / DCEN (instruction / data caches).' },
  'ADC1->JSQR':                   { desc: 'Injected Sequence Register, defining which channels run in an injected conversion. JL = sequence length − 1.' },
  'ADC1->CR2':                    { desc: 'Control Register 2: ADON (enable), JEXTEN (injected trigger polarity), JEXTSEL (trigger source), DMA, EOCS.' },
  'ADC1->JDR1':                   { desc: 'Injected Data Register 1, holding the first injected conversion result (phase A in our case).' },
  'ADC1->JDR2':                   { desc: 'Injected Data Register 2, holding the second injected result (phase B).' },
  'ADC1->SR':                     { desc: 'Status Register with JEOC (end-of-injected flag), EOC (regular), STRT, AWD (analog watchdog).' },
  'ADC_CR2_JEXTEN_0': { desc: 'ADC_CR2.JEXTEN[0]: with the rest of JEXTEN, picks the polarity of the injected trigger. 01 = rising edge.' },
  'ADC_CR2_JEXTSEL_0':{ desc: 'ADC_CR2.JEXTSEL[0]: with the rest of JEXTSEL, picks the trigger source. 0000 = TIM1 CC1, 0001 = TIM1 CC2, 0010 = TIM1 CC3, 0011 = TIM1 CC4, 0100 = TIM2 CC2, 1011 = TIM1 TRGO.' },
  'ADC_CR2_JSWSTART':{ desc: 'ADC_CR2.JSWSTART: software trigger of an injected conversion. Cleared by hardware when the conversion starts.' },
  'ADC_SR_JEOC':     { desc: 'ADC_SR.JEOC: set when the injected conversion finishes. Cleared by writing 0 or by reading JDRx.' },
  'TIM_BDTR_DTG_4':  { desc: 'DTG[4] in TIM_BDTR. DTG[7:5] picks the dead-time encoding range; the rest set the value. For 571 ns dead-time DTG = 0b00100100.' },
  'TIM_BDTR_DTG_2':  { desc: 'DTG[2] in TIM_BDTR. See DTG_4 for the encoding scheme.' },
  'TIM_BDTR_MOE':    { desc: 'Master Output Enable. The key bit that turns on the PWM outputs of an advanced timer. Without it, every CHx and CHxN stays in the idle state.' },
  'TIM_SR_UIF':      { desc: 'Update Interrupt Flag, raised on every PWM period (ARR overflow). The main trigger of the FOC ISR.' },
  'RCC_CR_HSEON':    { desc: 'RCC_CR.HSEON: turns on the external HSE crystal oscillator. Without it the STM32 stays on the internal HSI at 16 MHz.' },
  'RCC_CR_HSERDY':   { desc: 'RCC_CR.HSERDY: set once the HSE has stabilized (~2 ms after HSEON). Polled in the boot loop.' },
  'RCC_CR_PLLON':    { desc: 'RCC_CR.PLLON: turns on the PLL. PLLCFGR must already be set up.' },
  'RCC_CR_PLLRDY':   { desc: 'RCC_CR.PLLRDY: the PLL has locked and its output is ready.' },
  'RCC_CFGR_SW_PLL': { desc: 'RCC_CFGR.SW = 0b10: select the PLL as the SYSCLK source. Up until then the system was running off HSI or HSE.' },
  'FLASH_ACR_LATENCY_5WS': { desc: 'Sets flash wait states to 5. The F405 needs at least 5 WS at 168 MHz; below that flash reads come back wrong.' },
  'FLASH_ACR_PRFTEN': { desc: 'Enables the flash prefetch buffer. Hides part of the wait-state cost for linear code, raising effective execution speed.' },
  'pole_pairs':      { desc: 'Number of rotor pole pairs. The ET Max has 12 (24 magnetic poles). Electrical angle = pole_pairs × mechanical angle.' },
  'omega_elec':      { desc: 'Electrical rotor angular speed in rad/s. Used in the Park transform and in cross-coupling terms of the motor equations.' },
  'omega_mech':      { desc: 'Mechanical rotor angular speed in rad/s. omega_mech × tireRadius gives the wheel\'s linear speed.' },
  'V_max':           { desc: 'Maximum allowed magnitude of the voltage vector, bounded by the bus voltage. For SVPWM: V_max = V_bus / √3 ≈ 0.577 × V_bus.' },
  'V_bus':           { desc: 'DC bus (battery) voltage. The ET Max sits at ~150–168 V depending on charge. Drops under peak current because of internal resistance.' },
  'C_WINDING':       { desc: 'Thermal capacity of the copper winding in J/K. Small (~800 J/K) so the winding heats fast under I²R losses.' },
  'C_IRON':          { desc: 'Thermal capacity of the iron stator in J/K. Large (~5000 J/K), so it heats and cools slowly.' },
  'R_WI':            { desc: 'Winding-to-iron thermal resistance in K/W. The smaller it is, the better the stator pulls heat out of the winding.' },
  'R_IA':            { desc: 'Iron-to-ambient thermal resistance in K/W. Large for a sealed hub motor (~1.2 K/W), which is why cooldown takes so long.' },
  'TAU_FLUX':        { desc: 'HPF time constant of the flux integrator (~50 ms). Sets the cutoff at 1/(2π·τ) ≈ 3 Hz, filtering out DC offset to keep the integrator from drifting.' },
  'CALIB_SAMPLES':   { desc: 'Number of samples used for the gyro zero calibration (200). With ±2 LSB noise the average reaches ~0.14 LSB precision, equivalent to ~0.001 °/s.' },
  'MAX_PHASE_CURRENT': { desc: 'Hard hardware limit on phase current (500 A). Crossing it triggers a CUTOUT — the motor stays off until reboot.' },
  'SOFT_CURRENT_LIMIT':{ desc: 'Soft phase-current limit (380 A). The controller keeps the requested current within these bounds. Lowered through derate as the motor temperature rises.' },

  // --- FOC theory: cross-coupling, decoupling, PWM ---
  'БКПС':                  { desc: 'Russian for the cross-coupling decoupling block in FOC. Compensates the mutual influence of the D and Q axes by adding −ωe·Lq·Iq and +ωe·Ld·Id + ωe·Ψ to the PI outputs. Without it a fast Iq change disturbs Id, and vice versa.' },
  'Cross-coupling':        { desc: 'Cross-coupling in the PMSM equations: diq/dt depends on Id, and vice versa. It comes from the d/q frame rotating relative to the stator. At high speed it becomes the dominant effect.' },
  'cross-coupling':        { desc: 'Cross-coupling in the PMSM equations: diq/dt depends on Id, and vice versa. It comes from the d/q frame rotating relative to the stator. At high speed it becomes the dominant effect.' },
  'decoupling':            { desc: 'Decoupling — compensating cross-coupling in FOC. Adds the predictable disturbance terms to the PI outputs so that each axis sees a clean dynamic free of the other. Technically a feed-forward compensation.' },
  'feed-forward':          { desc: 'A signal added directly to the controller output, bypassing feedback. In decoupling: ωe·Lq·Iq and ωe·Ld·Id + ωe·Ψ are computed and added to the PI output.' },
  'common-mode':           { desc: 'The common component shared by all three phases. Plain sinusoidal PWM holds it at zero. SVPWM injects one (third harmonic or min/max injection) to extend the linear range by 15%.' },
  'modulation index':      { desc: 'Modulation index m = V_ref / V_max. The linear range of plain sinusoidal PWM is m ≤ 1. SVPWM extends it to m ≤ 2/√3 ≈ 1.155. Above that the output starts to distort (overmodulation).' },
  'overmodulation':        { desc: 'Operating with required voltage above what direct PWM can render. The output saturates, harmonics appear, torque pulsates. SVPWM pushes the threshold from m=1 to m=1.155.' },
  'third-harmonic injection': { desc: 'A way to extend the linear PWM range by ~15%. Each phase gets 1/6 of the third harmonic of the fundamental added to it. Since the same offset goes to all three phases, line-to-line voltages are unchanged. Equivalent in capability to SVPWM.' },
  'Edith Clarke':          { desc: 'Edith Clarke (1883–1959), the first woman electrical engineer and a professor at the University of Texas. She formulated the transform from three-phase to a two-phase equivalent (1937). Hence "Clarke transform" — not "Clarke\'s transform".' },
  'Park transform':        { desc: 'Park transform: from the stationary two-phase frame (α, β) to the rotating one (d, q). Named after Robert Park (1929). When the d axis is aligned with the rotor flux, all steady-state quantities become constants.' },
  'V_AB':                  { desc: 'Line-to-line voltage between phases A and B = Va − Vb. This is what the motor winding actually sees. The common-mode component of each phase (shared across all three) cancels in the subtraction.' },
  'phase voltage':         { desc: 'Voltage between a phase and the neutral (or the bus midpoint). Different from line-to-line. On a PMSM with floating neutral the line-to-line is √3 times the phase voltage for a sinusoidal system.' },
  'PI controller':         { desc: 'Proportional-integral controller: out = Kp·err + Ki·∫err·dt. The proportional term gives a fast response, the integral kills steady-state error. FOC runs two independent PIs on the D and Q axes.' },
  'anti-windup':           { desc: 'Integrator anti-windup: when the controller output saturates, the integrator stops growing. Without it, after a long saturation the controller cannot recover quickly — the integral has to be unloaded first.' },

  // --- Tools ---
  'Ghidra':    { desc: 'A reverse-engineering framework from the NSA. Open-source, free, with a built-in ARM/x86 decompiler. The main tool for digging into EUC firmware.' },
  'openocd':   { desc: 'Open On-Chip Debugger. Open-source, talks to ST-Link, J-Link and other adapters. Used for dumping and flashing STM32 over SWD.' },
  'OpenOCD':   { desc: 'Open On-Chip Debugger. Open-source, talks to ST-Link, J-Link and other adapters. Used for dumping and flashing STM32 over SWD.' },
  'gdb':       { desc: 'GNU Debugger. Native-code debugger that drives OpenOCD for ARM firmware debugging.' },
  'GDB':       { desc: 'GNU Debugger. Native-code debugger that drives OpenOCD for ARM firmware debugging.' },
  'ST-Link':   { desc: 'STM32 programmer/debugger from ST Microelectronics. AliExpress clones go for around $4.' },
  'VESC':      { desc: "Vedder's Electric Speed Controller. Open BLDC firmware by Benjamin Vedder. Powers skateboards, EUCs, electric boats." },
  'SimpleFOC': { desc: 'An educational FOC library for Arduino and STM32 HAL. Slower than production firmware, but the code is extremely readable.' },
  'IDA Pro':   { desc: 'Interactive DisAssembler. A commercial reverse-engineering tool, the alternative to Ghidra. License starts around $2,000.' },
  'PyGhidra':  { desc: 'Python bindings for Ghidra. Lets you write firmware-analysis scripts in Python instead of Java.' },
  'WheelLog':  { desc: 'Android app that logs EUC telemetry over BLE. Decodes 0x55AA packets and writes CSV.' },
  'EUC World': { desc: 'Android app for EUCs: telemetry, parameter tuning (Kp, Kd), OTA firmware updates, mapping and ride logging.' },

  // --- Misc concepts ---
  'pole pairs':{ desc: 'Pairs of rotor poles. A 24-pole motor has 12 pairs. Electrical angle = mechanical angle × pole pairs.' },
  'Pole pairs':{ desc: 'Pairs of rotor poles. A 24-pole motor has 12 pairs. Electrical angle = mechanical angle × pole pairs.' },
  'SoC':       { desc: 'Battery state of charge in percent. The BMS computes SoC from voltage and the integral of current.' },
  'CRC':       { desc: 'Cyclic redundancy check, a checksum for data integrity. YMODEM uses CRC-16.' },
  'DLPF':      { desc: 'Built-in digital low-pass filter inside the MPU6500 for sensor data. Configured through register 0x1A.' },
  'FIFO':      { desc: 'First-in, first-out queue. The MPU6500 has a 1024-byte FIFO inside for buffering high-rate data.' },
}
